export const ADD_LOGINFO = "ADD_LOGINFO";
export const REMOVE_LOGINFO = "REMOVE_LOGINFO";
export const ADD_USER_SELECTION = "ADD_USER_SELECTION";
export const REMOVE_USER_SELECTION = "REMOVE_USER_SELECTION";
export const ADD_ACCOUNT_360_PAGE = "ADD_ACCOUNT_360_PAGE";
export const REMOVE_ACCOUNT_360_PAGE = "REMOVE_ACCOUNT_360_PAGE";
export const ADD_ACCOUNT_360_NUMBER = "ADD_ACCOUNT_360_NUMBER";
export const REMOVE_ACCOUNT_360_NUMBER = "REMOVE_ACCOUNT_360_NUMBER";
export const ADD_ACCOUNT_360_CLIENT_DETAILS = "ADD_ACCOUNT_360_CLIENT_DETAILS";
export const REMOVE_ACCOUNT_360_CLIENT_DETAILS =
  "REMOVE_ACCOUNT_360_CLIENT_DETAILS";
export const ADD_OPS_360_PAGE_DETAILS = "ADD_OPS_360_PAGE_DETAILS";
export const REMOVE_OPS_360_PAGE_DETAILS = "REMOVE_OPS_360_PAGE_DETAILS";
export const ADD_ACCOUNT_360_PAGE_DETAILS = "ADD_ACCOUNT_360_PAGE_DETAILS";
export const REMOVE_ACCOUNT_360_PAGE_DETAILS =
  "REMOVE_ACCOUNT_360_PAGE_DETAILS";
export const ADD_CUSTOMER_360_PAGE_DETAILS = "ADD_CUSTOMER_360_PAGE_DETAILS";
export const REMOVE_CUSTOMER_360_PAGE_DETAILS =
  "REMOVE_CUSTOMER_360_PAGE_DETAILS";
