# server:
#   port: 8761
# spring:
#   application:
#     name: eurekaserver
# eureka:
#   client:
#     registerWithEureka: false
#     fetchRegistry: false
spring:
  config:
    activate:
      on-profile: default
  application:
      name: eurekaserver
  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false
  server:
    port: 8761
---
spring:
  config:
    activate:
      on-profile: dev
  application:
      name: eurekaserver
  eureka:
    client:
      registerWithEureka: false
      fetchRegistry: false