apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      imagePullSecrets:
        - name: harbor-creds
      containers:
        - name: apigateway
          image: 172.16.238.56/newcustomer360/apigateway:
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev" 

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - bnubukubcwn1

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: apigateway