export const caseSummaryColumn = [
  // {
  //   field: "number",
  //   headerName: "No",
  //   sortable: true,
  //   filter: true,
  //   width: 75,
  //   tooltipField: "number",
  // },
  {
    field: "customerId",
    headerName: "Customer Id",
    sortable: true,
    filter: true,
    width: 130,
    tooltipField: "customerId",
    headerTooltip: "Customer Id",
  },
  {
    field: "status",
    headerName: "Status",
    sortable: true,
    filter: true,
    width: 130,
    tooltipField: "status",
    headerTooltip: "Status",
  },
  {
    field: "type",
    headerName: "Type",
    sortable: true,
    filter: true,
    width: 90,
    tooltipField: "type",
    headerTooltip: "Type",
  },
  {
    field: "category",
    headerName: "Category",
    sortable: true,
    filter: true,
    width: 130,
    tooltipField: "category",
    headerTooltip: "Category",
  },
  {
    field: "subCategory",
    headerName: "Sub category",
    sortable: true,
    filter: true,
    width: 140,
    tooltipField: "subCategory",
    headerTooltip: "Sub category",
  },
  {
    field: "subSubCategory",
    headerName: "Sub sub category",
    sortable: true,
    filter: true,
    width: 140,
    tooltipField: "subSubCategory",
    headerTooltip: "Sub sub category",
  },
  {
    field: "dueDate",
    headerName: "Due date",
    sortable: true,
    filter: true,
    width: 120,
    tooltipField: "dueDate",
    headerTooltip: "Due date",
  },
];

export const CreateTaskColumns = [
  {
    field: "title",
    headerName: "Title",
    sortable: false,
    filter: false,
    wrapText: true,
    cellStyle: { lineHeight: 1.5 },
    minWidth: 30,
    width: 130,
    flex: 1,
  },
  {
    field: "scenario",
    headerName: "Scenario",
    sortable: false,
    filter: false,
    wrapText: true,
    cellStyle: { lineHeight: 1.5 },
    minWidth: 50,
    width: 130,
    flex: 1,
  },
  {
    field: "taskMessage",
    headerName: "Task Message",
    sortable: false,
    filter: false,
    wrapText: true,
    autoHeight: true,
    cellStyle: { lineHeight: 1.5 },
    minWidth: 100,
    width: 650,
    flex: 4,
  },
  {
    field: "status",
    headerName: "Status",
    sortable: false,
    filter: false,
    cellStyle: { lineHeight: 1.5 },
    cellEditor: "agSelectCellEditor",
    cellEditorParams: {
      values: ["Open", "Close"],
    },
    minWidth: 50,
    width: 130,
    flex: 1,
  },
];
