server:
  port: 8080
spring:
    config:
        activate:
            on-profile: default
    application:
        name: customer360
    sql:
        init:
            mode: always
    datasource:
        initialization-mode: always
        schema: classpath:schema.sql
        url: jdbc:mysql://localhost:3306/customer360
        username: root
        password: root
        data: classpath:data.sql
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: none
        show-sql: true
    cloud:
        compatibility-verifier:
            enabled: false
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  application:
#      name: customer360
#  datasource:
#    url: jdbc:mysql://mysql.mysql.svc.cluster.local:3306/customer360
#    username: application
#    password: customer360sql
#  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  cloud:
#    compatibility-verifier:
#      enabled: false
#
#    cloud:
#        compatibility-verifier:
#            enabled: false
eureka:
    instance:
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka