import {
  TEXT_FILTER_PARAMS,
  SORT_PARAMS,
  NUMBER_FILTER_PARAMS,
  DATE_FILTER_PARAMS,
} from "../../common/ColumnStructure";

export const caseAssignCol = [];
export const makeDepositWithdrawalCasesCol = [
  {
    field: "caseId",
    headerName: "Case ID",
    tooltipField: "caseId",
    headerTooltip: "Case ID",
    headerCheckboxSelection: true,
    checkboxSelection: true,
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "transactionType",
    headerName: "Transaction Type",
    headerTooltip: "Transaction Type",
    tooltipField: "transactionType",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "channel",
    headerName: "Channel",
    headerTooltip: "Channel",
    tooltipField: "channel",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "accountNo",
    headerName: "Account Number",
    headerTooltip: "Account Number",
    tooltipField: "accountNo",
    ...SORT_PARAMS,
    ...NUMBER_FILTER_PARAMS,
  },
  {
    field: "caseStatus",
    headerName: "Case Status",
    headerTooltip: "Case Status",
    tooltipField: "caseStatus",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "createdDate",
    headerName: "Created Date",
    headerTooltip: "Created Date",
    tooltipField: "createdDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdMaker",
    headerName: "Agent ID - Maker",
    headerTooltip: "Agent ID - Maker",
    tooltipField: "agentIdMaker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "approvedOrRejectedDate",
    headerName: "Approved/Rejected Date",
    headerTooltip: "Approved/Rejected Date",
    tooltipField: "approvedOrRejectedDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdChecker",
    headerName: "Agent ID - Checker",
    headerTooltip: "Agent ID - Checker",
    tooltipField: "agentIdChecker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "rejectReason",
    headerName: "Reject Reason",
    headerTooltip: "Reject Reason",
    tooltipField: "rejectReason",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
];
export const approveClsLockCasesCol = [
  {
    field: "caseId",
    headerName: "Case ID",
    tooltipField: "caseId",
    headerTooltip: "Case ID",
    headerCheckboxSelection: true,
    checkboxSelection: true,
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "operationType",
    headerName: "Operation Type",
    headerTooltip: "Operation Type",
    tooltipField: "operationType",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "accountNo",
    headerName: "Account Number",
    headerTooltip: "Account Number",
    tooltipField: "accountNo",
    ...SORT_PARAMS,
    ...NUMBER_FILTER_PARAMS,
  },
  {
    field: "caseStatus",
    headerName: "Case Status",
    headerTooltip: "Case Status",
    tooltipField: "caseStatus",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "createdDate",
    headerName: "Created Date",
    headerTooltip: "Created Date",
    tooltipField: "createdDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdMaker",
    headerName: "Agent ID - Maker",
    headerTooltip: "Agent ID - Maker",
    tooltipField: "agentIdMaker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "approvedOrRejectedDate",
    headerName: "Approved/Rejected Date",
    headerTooltip: "Approved/Rejected Date",
    tooltipField: "approvedOrRejectedDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdChecker",
    headerName: "Agent ID - Checker",
    headerTooltip: "Agent ID - Checker",
    tooltipField: "agentIdChecker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "rejectReason",
    headerName: "Reject Reason",
    headerTooltip: "Reject Reason",
    tooltipField: "rejectReason",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
];
export const applyAccuredInterestCasesCol = [
  {
    field: "caseId",
    headerName: "Case ID",
    tooltipField: "caseId",
    headerTooltip: "Case ID",
    headerCheckboxSelection: true,
    checkboxSelection: true,
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "interestApplicationDate",
    headerName: "Interest Application Date",
    headerTooltip: "Interest Application Date",
    tooltipField: "interestApplicationDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "accountNo",
    headerName: "Account Number",
    headerTooltip: "Account Number",
    tooltipField: "accountNo",
    ...SORT_PARAMS,
    ...NUMBER_FILTER_PARAMS,
  },
  {
    field: "caseStatus",
    headerName: "Case Status",
    headerTooltip: "Case Status",
    tooltipField: "caseStatus",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "createdDate",
    headerName: "Created Date",
    headerTooltip: "Created Date",
    tooltipField: "createdDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdMaker",
    headerName: "Agent ID - Maker",
    headerTooltip: "Agent ID - Maker",
    tooltipField: "agentIdMaker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "approvedOrRejectedDate",
    headerName: "Approved/Rejected Date",
    headerTooltip: "Approved/Rejected Date",
    tooltipField: "approvedOrRejectedDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdChecker",
    headerName: "Agent ID - Checker",
    headerTooltip: "Agent ID - Checker",
    tooltipField: "agentIdChecker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "rejectReason",
    headerName: "Reject Reason",
    headerTooltip: "Reject Reason",
    tooltipField: "rejectReason",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
];
export const applyAccountFeeCasesCol = [
  {
    field: "caseId",
    headerName: "Case ID",
    tooltipField: "caseId",
    headerTooltip: "Case ID",
    headerCheckboxSelection: true,
    checkboxSelection: true,
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "productName",
    headerName: "Product Name",
    headerTooltip: "Product Name",
    tooltipField: "productName",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "feeType",
    headerName: "Fee Type",
    headerTooltip: "Fee Type",
    tooltipField: "feeType",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "accountNo",
    headerName: "Account Number",
    headerTooltip: "Account Number",
    tooltipField: "accountNo",
    ...SORT_PARAMS,
    ...NUMBER_FILTER_PARAMS,
  },
  {
    field: "caseStatus",
    headerName: "Case Status",
    headerTooltip: "Case Status",
    tooltipField: "caseStatus",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "createdDate",
    headerName: "Created Date",
    headerTooltip: "Created Date",
    tooltipField: "createdDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdMaker",
    headerName: "Agent ID - Maker",
    headerTooltip: "Agent ID - Maker",
    tooltipField: "agentIdMaker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "approvedOrRejectedDate",
    headerName: "Approved/Rejected Date",
    headerTooltip: "Approved/Rejected Date",
    tooltipField: "approvedOrRejectedDate",
    ...SORT_PARAMS,
    ...DATE_FILTER_PARAMS,
  },
  {
    field: "agentIdChecker",
    headerName: "Agent ID - Checker",
    headerTooltip: "Agent ID - Checker",
    tooltipField: "agentIdChecker",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
  {
    field: "rejectReason",
    headerName: "Reject Reason",
    headerTooltip: "Reject Reason",
    tooltipField: "rejectReason",
    ...SORT_PARAMS,
    ...TEXT_FILTER_PARAMS,
  },
];
