apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      imagePullSecrets:
        - name: harbor-creds
      containers:
        - name: eurekaserver
          image: 172.16.238.56/newcustomer360/eurekaserver:
          ports:
            - containerPort: 8671
          env:
            # - name: DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: db-credentials
            #       key: username
            # - name: DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: db-credentials
            #       key: password
            # - name: DB_URL
            #   value: "jdbc:mysql://mysql.mysql.svc.cluster.local:3306/customer360"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev" 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - bnubukubcwn1
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eurekaserver